### PR TITLE
correct version and package manpages

### LINKED ISSUE #53: gh version == dev
```bash
$ gh version
gh version DEV
https://github.com/cli/cli/releases/latest
```

Not sure if this is from here or from upstream. 

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by matthiasdiener**
Fixes #53 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@matthiasdiener could you please explain to me why this happened 🙃 

Trying to learn more about building in go

**Comment by ngam** [comment]
Also... is the date in parentheses supposed to be build date?

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=432550&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=260

**Comment by matthiasdiener** [comment]
> @matthiasdiener could you please explain to me why this happened 🙃

I'm not 100% certain, but it seems that `GH_VERSION` is only used when using `script/build.go` to compile `gh`, which wasn't done before.

**Comment by matthiasdiener** [comment]
> Also... is the date in parentheses supposed to be build date?

I believe so, yes.

**Pull request merged**
